project:
  type: website
  output-dir: docs

website:
  title: "Cameron Cornforth's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: source